version: '3'

services:
  magento:
    image: gpressutto5/magento-ebanx
    container_name: magento
    ports:
      - ${MAGENTO_EXTERNAL_PORT:-80}:80
      - ${XDEBUG_EXTERNAL_PORT:-9000}:9000
    links:
      - magento_db
    env_file:
      - env
    depends_on: 
      - mysql
  magento_db:
    image: mysql:5.6.23
    container_name: magento_db
    ports:
      - ${MYSQL_EXTERNAL_PORT:-3306}:3306
    env_file:
      - env
